### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by AdedayoOpeyemi** [AdedayoOpeyemi/js-capstone-api#19]
Choose images, text, icons, fonts.

**Comment by nelsinofrancisco** [comment]
Issue Solved:

- We're gonna to retrieve the books images from the API;
- Text will be properly decided when we start working and selecting the categories of books we want to show;
- Icons will be provided by FontAwesome;
- We're gonna use fonts that are common like Roboto and for the titles Merriweather;
